In [3]:
%matplotlib inline

import numpy as np
import pylab as plt
import pandas as pd

In [6]:
!ls ../datasets/

2014_world_gdp_with_codes.csv  migrants.csv
diabetes.csv		       monthly-milk-production-pounds.csv
disease.csv		       significant-earthquakes.csv
earthquake.csv		       su5m.csv
gapminderDataFiveYear.csv      tesla-stock-price.csv
maternal_health.csv

In [8]:
pd.read_csv('../datasets/tesla-stock-price.csv')

           date   close         volume    open      high       low
0         11:34  270.49      4,787,699  264.50  273.8800  262.2400
1    2018/10/15  259.59   6189026.0000  259.06  263.2800  254.5367
2    2018/10/12  258.78   7189257.0000  261.00  261.9900  252.0100
3    2018/10/11  252.23   8128184.0000  257.53  262.2500  249.0300
4    2018/10/10  256.88  12781560.0000  264.61  265.5100  247.7700
5    2018/10/09  262.80  12037780.0000  255.25  266.7700  253.3000
6    2018/10/08  250.56  13371180.0000  264.52  267.7599  249.0000
7    2018/10/05  261.95  17900710.0000  274.65  274.8800  260.0000
8    2018/10/04  281.83   9638885.0000  293.95  294.0000  277.6700
9    2018/10/03  294.80   7982272.0000  303.33  304.6000  291.5700
10   2018/10/02  301.02  11699690.0000  313.95  316.8400  299.1500
11   2018/10/01  310.70  21714210.0000  305.77  311.4400  301.0500
12   2018/09/28  264.77  33597290.0000  270.26  278.0000  260.5550
13   2018/09/27  307.52   7337760.0000  312.90  314.9600  306.9100
14   2018/09/26  309.58   7835863.0000  301.91  313.8900  301.1093
15   2018/09/25  300.99   4472287.0000  300.00  304.6000  296.5000
16   2018/09/24  299.68   4834384.0000  298.48  302.9993  293.5800
17   2018/09/21  299.10   5038497.0000  297.70  300.5800  295.3700
18   2018/09/20  298.33   7332477.0000  303.56  305.9800  293.3300
19   2018/09/19  299.02   8264353.0000  280.51  300.0000  280.5000
20   2018/09/18  284.96  16494280.0000  296.69  302.6400  275.5000
21   2018/09/17  294.84   6866208.0000  290.04  300.8700  288.1300
22   2018/09/14  295.20   6757652.0000  288.76  297.3256  286.5200
23   2018/09/13  289.46   6333281.0000  288.02  295.0000  285.1800
24   2018/09/12  290.54  10002150.0000  281.44  292.5000  278.6463
25   2018/09/11  279.44   9161061.0000  279.47  282.0000  273.5500
26   2018/09/10  285.50  14232250.0000  273.26  286.0300  271.0000
27   2018/09/07  263.24  22442310.0000  260.10  268.3500  252.2548
28   2018/09/06  280.95   7472756.0000  284.80  291.1700  278.8800
29   2018/09/05  280.74   7707342.0000  285.05  286.7800  277.1800
..          ...     ...            ...     ...       ...       ...
727  2015/11/25  229.64   3986945.0000  221.34  230.8250  220.3750
728  2015/11/24  218.25   2478389.0000  215.37  221.0000  215.0000
729  2015/11/23  217.75   2525196.0000  217.35  219.1800  214.6798
730  2015/11/20  220.01   4394199.0000  223.49  225.0000  213.5800
731  2015/11/19  221.80   2499593.0000  220.54  226.1900  220.3000
732  2015/11/18  221.07   2810200.0000  214.50  221.3800  212.5200
733  2015/11/17  214.00   2148326.0000  215.20  216.0000  211.4000
734  2015/11/16  214.31   2920362.0000  206.09  214.9800  205.8000
735  2015/11/13  207.19   3423139.0000  212.95  212.9900  206.5200
736  2015/11/12  212.94   2913511.0000  217.85  219.0000  212.6600
737  2015/11/11  219.08   3337501.0000  217.77  219.4800  213.6300
738  2015/11/10  216.50   4612408.0000  223.48  223.7000  216.0800
739  2015/11/09  225.33   3846179.0000  232.99  232.9900  224.3100
740  2015/11/06  232.36   2444264.0000  230.70  233.3590  229.5000
741  2015/11/05  231.77   4494944.0000  230.58  234.5843  229.1900
742  2015/11/04  231.63  12713530.0000  227.00  232.7400  225.2000
743  2015/11/03  208.35   8065091.0000  213.85  214.4400  207.7500
744  2015/11/02  213.79   3924514.0000  208.92  215.8000  207.2200
745  2015/10/30  206.93   4432433.0000  210.40  211.6300  203.8900
746  2015/10/29  211.63   1794743.0000  211.75  213.7481  210.6400
747  2015/10/28  212.96   2726880.0000  211.31  213.4500  208.3000
748  2015/10/27  210.35   3512832.0000  214.84  217.1000  207.5100
749  2015/10/26  215.26   3388227.0000  211.38  215.8800  210.0000
750  2015/10/23  209.09   4226411.0000  215.00  215.3500  207.6900
751  2015/10/22  211.72   2818801.0000  211.56  215.7500  209.4000
752  2015/10/21  210.09   4177956.0000  211.99  214.8100  208.8000
753  2015/10/20  213.03  14877020.0000  227.72  228.6000  202.0000
754  2015/10/19  228.10   2506836.0000  226.50  231.1500  224.9400
755  2015/10/16  227.01   4327574.0000  223.04  230.4805  222.8700
756  2015/10/15  221.31   2835920.0000  216.43  221.7300  213.7000

[757 rows x 6 columns]

In [36]:
df = pd.read_csv('../datasets/monthly-milk-production-pounds.csv')
# df
# df.plot('Month','Monthly milk production (pounds per cow)', kind='line')

In [72]:
df = pd.read_csv('../datasets/significant-earthquakes.csv')
df

,Entity,Code,Year,Number of significant earthquakes (significant earthquakes)
0,Afghanistan,AFG,-2150,0
1,Afghanistan,AFG,-2000,0
2,Afghanistan,AFG,-1610,0
3,Afghanistan,AFG,-1566,0
4,Afghanistan,AFG,-1450,0
5,Afghanistan,AFG,-1365,0
6,Afghanistan,AFG,-1250,0
7,Afghanistan,AFG,-1050,0
8,Afghanistan,AFG,-759,0
9,Afghanistan,AFG,-590,0
10,Afghanistan,AFG,-550,0
11,Afghanistan,AFG,-525,0
12,Afghanistan,AFG,-480,0
13,Afghanistan,AFG,-479,0
14,Afghanistan,AFG,-432,0
15,Afghanistan,AFG,-426,0
16,Afghanistan,AFG,-400,0
17,Afghanistan,AFG,-373,0
18,Afghanistan,AFG,-364,0
19,Afghanistan,AFG,-330,0
20,Afghanistan,AFG,-326,0
21,Afghanistan,AFG,-282,0
22,Afghanistan,AFG,-250,0
23,Afghanistan,AFG,-227,0
24,Afghanistan,AFG,-223,0
25,Afghanistan,AFG,-221,0
26,Afghanistan,AFG,-218,0
27,Afghanistan,AFG,-217,0
28,Afghanistan,AFG,-210,0
29,Afghanistan,AFG,-198,0
...,...,...,...,...
143610,Zambia,ZMB,1988,0
143611,Zambia,ZMB,1989,0
143612,Zambia,ZMB,1990,0
143613,Zambia,ZMB,1991,0
143614,Zambia,ZMB,1992,0
143615,Zambia,ZMB,1993,0
143616,Zambia,ZMB,1994,0
143617,Zambia,ZMB,1995,0
143618,Zambia,ZMB,1996,0
143619,Zambia,ZMB,1997,0
143620,Zambia,ZMB,1998,0
143621,Zambia,ZMB,1999,0
143622,Zambia,ZMB,2000,0
143623,Zambia,ZMB,2001,0
143624,Zambia,ZMB,2002,0
143625,Zambia,ZMB,2003,0
143626,Zambia,ZMB,2004,0
143627,Zambia,ZMB,2005,0
143628,Zambia,ZMB,2006,0
143629,Zambia,ZMB,2007,0
143630,Zambia,ZMB,2008,0
143631,Zambia,ZMB,2009,0
143632,Zambia,ZMB,2010,0
143633,Zambia,ZMB,2011,0
143634,Zambia,ZMB,2012,0
143635,Zambia,ZMB,2013,0
143636,Zambia,ZMB,2014,0
143637,Zambia,ZMB,2015,0
143638,Zambia,ZMB,2016,0
143639,Zambia,ZMB,2017,0

In [73]:
df = pd.read_csv('../datasets/earthquake.csv')
df

,Unknown Number of Deaths,0 Deaths,1-50 Deaths,51-100 Deaths,101-1000 Deaths,>1001 Deaths,"Unknown Number of Deaths, lat","Unknown Number of Deaths, lon","0 Deaths, lat","0 Deaths, lon","1-50 Deaths, lat","1-50 Deaths, lon","51-100 Deaths, lat","51-100 Deaths, lon","101-1000 Deaths, lat","101-1000 Deaths, lon",">1001 Deaths, lat",">1001 Deaths, lon"
0,"New Caledonia: Noumea; Vanuatu: Port-Vila, 1995","Solomon Islands: Santa Cruz Islands; Vanuatu,...","Philippines: Mindanao: Talakag-Malaybalay, 1987","Switzerland, 1801","Switzerland, 1584","Philippines: Mindanao: S, 1976",-23.008,169.9,-12.584,166.676,8.047,125.410,46.900,8.600,46.3,7,6.292,124.09
1,"Pakistan: Battagram, 2015","Iran: Western: Masjed-E- Soleyman, 2003","Pakistan: Quetta, Nushki, 1978","Venezuela: Cariaco-Cumana, 1997","Switzerland, 1584","China: Sichuan Province: Kangding, 1725",34.658,73.302,31.953,49.209,29.926,66.302,10.598,-63.486,46.2,7,30.1,101.9
2,"Peru, 1852",NaN,"Tonga Trench, 1977","Peru: Maca, Chivay, Yanque, 1991","El Salvador: San Marcos, 1965","Iran: Quchan, 1872",-12.1,-77.1,NaN,NaN,-22.878,-175.900,-15.679,-71.574,13.5,-89.3,37.3,58.3
3,"Chile: Southern, 1965",NaN,"Honduras-Guatemala-El Salvador, 1982","Japan: Off East Coast Of Honshu Island, 1968","China: Sichuan Province, 1933","Iran: Quchan, 1871",-42.9,-75.13,NaN,NaN,14.487,-89.121,40.800,143.200,29.5,102.5,37.3,58.3
4,"Indonesia: Banda Sea, 1925",NaN,"China: Gansu Province: Tianzhu, 1990","China: Shanxi Province: Anyi, Gueheng, 1505","China: Guizhou Province: Qinglong, 1551","Iran: Tabriz, 1779",-8,115,NaN,NaN,37.093,103.781,35.200,110.900,25.8,105.2,38,46.7
5,"Russia: Makhachkala, Dagestan, 1999",NaN,"Afghanistan: Hindu Kush: Pik Lenina, 1990","China: Yunnan Province: Anning, Yuxi, 1507","China: Jiangxi Province: Yen Hi Chan, 1361","Iran: Ardabil, 1997",42.962,46.954,NaN,NaN,36.415,70.789,24.600,102.500,28.8,115.3,38.075,48.05
6,"Micronesia, Fed. States Of: Yap Is, Caroline ...",NaN,"Costa Rica-Panama, 1941","China: Shaanxi Province: Tongguan, 1789","Afghanistan: Hindu Kush: Tashiak, Termiz, 1994","Iran: Rasht, Qazvin, Zanjan, Rudbar, Manjil,...",None,None,NaN,NaN,8.7,-83.200,34.600,110.300,36.901,67.163,36.957,49.409
7,"Chile: Central, Valparaiso, 1986",NaN,"Afghanistan: Hindu Kush: Chitral, Mardan, Ma...","Switzerland, 1622","Indonesia: Sumatra: Bengkulu, Enggano, 2000","Iran: Saimareh, 871",-33.071,-72.084,NaN,NaN,35.121,70.486,46.800,10.300,-4.721,102.087,33.2,47.2
8,"Chile: Antofagasta, 1957",NaN,"Taiwan: Hualien, Taipei, 1990","Mexico: Sw Coast: Mexico City, 1985","Peru: Moyabamba-Riojo, 1990","Iran: Taheri (Siraf), 978",-23.5,-71.5,NaN,NaN,23.916,121.636,17.802,-101.647,-6.016,-77.229,27.7,52.3
9,"Italy: Tyrrhenian Calabria, 1783",NaN,"Philippines: Santiago, 1990","Switzerland, 1851",El Salvador: San Juan Tepezontes-San Vicente-C...,"China: Yunnan Province: Yiliang, 1560",38.9,17.1,NaN,NaN,9.253,125.606,46.300,8.000,13.671,-88.938,24.9,103.2
10,"Micronesia, Fed. States Of: Caroline Islands,...",NaN,"Peru: Santaog De Chuco, Trujillo, Chimbote, 1987","China: Gansu Province: Wusban, 1850","China: Shanxi Province, 1664","Pakistan: Balakot, Patan, 1974",7,138,NaN,NaN,-8.143,-77.954,34.700,104.900,38.7,112.7,35.1,72.9
11,"California: Terminal Island, 1955",NaN,"Afghanistan: Khorog, Jalalabad; Pakistan, 1984","Turkey: Burdur, 1971","Peru: Santa Catalina, 1739","Iran: Qeshm Island, Larak Island, 1897",33.8,-118.2,NaN,NaN,34.616,70.484,37.600,29.800,-14.1,-73.2,26.95,56.26
12,"Guam; Northern Mariana Islands: Saipan, 1990",NaN,"Peru: Huarmey, Casma, Huarax, Chimbote, 1986","Turkey: Pasinler (Hasankale),Erzincan, 1952","China: Hebei Province: Dongguang, Cangxian, ...","India: Chamoli, Uttarkashi, New Delhi, Chandi...",15.125,147.596,NaN,NaN,-9.505,-77.512,39.800,39.500,38,116.5,30.78,78.774
13,"New Zealand: Off Coast North Island, 1947",NaN,"Turkey: Denizli, 1976","Mexico: Acapulco,Mexico City, 1957","Taiwan: Tainan, 1720","India: Latur-Osmanabad, Killari, 1993",-38.85,178.87,NaN,NaN,37.7,28.890,16.500,-99.100,20.3,120.3,18.066,76.451
14,"Peru: Northern: Chimbote, Callao, 1996",NaN,"Philippines: Cebu Island, Mactan Island, 1922","China: Sichuan Province, 1738","China: Gansu Province, 1677","Pakistan: Muzaffarabad, Uri, Anantnag, Baramu...",-9.593,-79.587,NaN,NaN,10.2,124.100,33.200,104.200,33.4,104.8,34.539,73.588
15,"Russia: Sea Of Okhotsk, 1902",NaN,"Chile: Catalina, Antofagasta, 1971","Greece: Samos (Dodecanese), 1831","China: Yunnan Province: Fumin, 1927","China: Guangdong Province: Yangjiang County,...",50,148,NaN,NaN,-25.5,-69.200,37.800,27.000,25.2,102.5,22.317,111.8
16,"Italy: Genoa, Carmagnole, 1703",NaN,"Japan: Honshu: W Coast, 1964","Switzerland, 1839","Iran: Khvoy (Khoy), 1843","Yemen: Razih, 1941",44.4,8.917,NaN,NaN,38.65,139.200,45.900,6.100,38.6,44.9,16.4,43.5
17,"Russia: Kuril-Japan: Hokkaido, 1974",NaN,"Dominican Republic: Santo Domingo, 1984","Chile: Peru: Tacna,Arica,Arequipa, 1831","China: Qinghai Province, 1893","Nepal-India: Kathmandu, Bihar, 1988",43.2,146.7,NaN,NaN,17.984,-69.338,-18.500,-71.000,36.6,101.8,26.755,86.616
18,"Mexico: Near Coast Of Guerrero, 1911",NaN,"Chile, 1956","China: Qinghai Province, 1834","China: Anhui Province, 1829","Taiwan: Mialoi, 1935",17,-100.7,NaN,NaN,-19,-70.000,33.000,97.000,33.2,117.9,24.3,120.8
19,"Japan: S Honshu: Hiroshima, 1978",NaN,"Philippines: Pagadian, Zamboanga, 1985","Greece: Kyparissia (Messinia), 1875","China: Yunnan Province, 1906","Iran: Torbet-I-Kheydarly, 1932",35.1,132.6,NaN,NaN,7.758,123.544,37.300,21.800,26.6,104.1,36.6,53.4
20,"Taiwan, 1994",NaN,"Papua New Guinea: New Britain: Rabaul, 1989","China: Shanxi Province, 1862","China: Yunnan Province, 1863","Yemen: Dhamar, 1982",23.959,122.448,NaN,NaN,-4.346,152.797,35.500,111.500,26,100.1,14.701,44.379
21,"Indonesia: Amurang Island, 1930",NaN,"Kazakhstan: Ust, Zaysan, 1990","China: Anhui Province, 1868","China: Hubei Province, 1856","Armenia: Zangezur, Nakhitchevan, 1931",1.2,124.57,NaN,NaN,47.869,85.076,32.400,117.800,29.7,108.8,39.2,46
22,"Boston And Salem, Massachusetts, 1668",NaN,"Taiwan: Chia-I, Tainan, Hualien, Kao-Hsiung, ...","Philippines: Cotabato,N Coast Of Illana Bay, ...","Taiwan: Jiayi, Kagi, 1776","China: Shaanxi Province: Lintong, Xianyang, ...",42.35,-71.05,NaN,NaN,23.407,120.736,7.000,124.000,23.5,120.6,34.4,108.9
23,"China: Ganzhou Province: Xunwu, 1987",NaN,"Georgia: Khekheti, 1991","Turkey: Van,Nemrut, 1881","China: Sichuan Province, 1854","Iran: Tabriz, 1727",24.924,115.608,NaN,NaN,42.565,43.349,38.500,43.300,29.1,107.1,38,46.3
24,"Russia: Kuril Islands, 1978",NaN,"Chile: Arica; Peru: Arequipa, Tacna, 1987","China: Yunnan Province, 1878","Iran: Tabriz, 1883","China: Sichuan Province, 1816",44.026,149.002,NaN,NaN,-17.897,-70.931,27.700,100.800,38.1,46.3,31.4,100.7
25,"South Africa: Mount Frere, Durban, 1986",NaN,"Japan: Tokkaido, Oshima, 1978","China: Shanxi Province, 1937","Ecuador: Gonzanama, San Pedro, Molleture, 1913","Israel: Palestine; Syria, 1752",-30.546,28.737,NaN,NaN,34.809,139.259,37.800,112.500,-3.4,-79.6,31.2,34.2
26,"Papua New Guinea: Admiralty Islands, 1977",NaN,"Azerbaijan: Agdas, Ucar, Agali, 1999","China: Shanxi Province, 1827","Turkey: Van,Bolgesi, 1945","Syria: Coast; Israel, 1752",-1.081,146.23,NaN,NaN,40.802,47.448,34.900,111.100,38.5,43.3,35,36
27,"California: Off Coast Northern, 2005",NaN,"Taiwan: Hualien, 1972","China: Shanxi Province: Xugou, 1368","Turkey: Aelana, Ceyhan, Adana, 1945","China: Shaanxi Province: Longxian, 1704",41.301,-125.97,NaN,NaN,23.6,121.600,37.600,112.500,37.4,35.8,34.9,106.8
28,"Peru: Central, 2006",NaN,"Mexico: Nw, 1980","China: S Xinjiang: Wuqua-Shufu, 1985","China: Qinghai Province, 1819","China: Hunan Province, 1631",-13.457,-76.677,NaN,NaN,32.22,-114.985,39.431,75.224,36.1,102.3,29.3,111.7
29,"Philippines: Celebes Sea: Moro Gulf, 2010",NaN,"China: Gansu Province: Lintao, 1631","Iran: St Thaddeus; Armenia: Ararat, Sini, An...","China: Yunnan Province, 1926","Iran: Mashhad, Neyshabur (Nishapur), 1673",6.486,123.467,NaN,NaN,35.3,104.300,39.100,44.500,25.6,100.3,36.3,59.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3472,"Nicaragua: Nagarote, Managua, 2014",NaN,NaN,NaN,NaN,NaN,12.514,-86.379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3473,"Solomon Islands, 2014",NaN,NaN,NaN,NaN,NaN,-11.315,162.211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3474,"Solomon Islands, 2014",NaN,NaN,NaN,NaN,NaN,-11.451,162.069,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3475,"Nicaragua: Managua, Ciudad Sandino, 2014",NaN,NaN,NaN,NaN,NaN,12.176,-86.296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3476,"Mexico: Guerrero; Mexico City, 2014",NaN,NaN,NaN,NaN,NaN,17.552,-100.816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3477,"Papua New Guinea: Solomon Sea, 2014",NaN,NaN,NaN,NaN,NaN,-6.72,154.931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3478,"Thailand: Chiang Rai, 2014",NaN,NaN,NaN,NaN,NaN,19.703,99.683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3479,"Mexico: Tecpan, 2014",NaN,NaN,NaN,NaN,NaN,17.385,-100.656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3480,"Germany: Hesse, 2014",NaN,NaN,NaN,NaN,NaN,49.915,8.624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3481,"Albania: Belsh, 2014",NaN,NaN,NaN,NaN,NaN,40.977,19.879,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3482,"China: Yunnan Province: Yingjiang, 2014",NaN,NaN,NaN,NaN,NaN,24.976,97.865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3483,"New Zealand: Sse Of Raoul Island, 2014",NaN,NaN,NaN,NaN,NaN,-30.118,-177.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3484,"Alaska: Aleutian Islands, 2014",NaN,NaN,NaN,NaN,NaN,51.797,178.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3485,"Japan: Sanriku, 2014",NaN,NaN,NaN,NaN,NaN,37.04,142.425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3486,"Alaska, 2014",NaN,NaN,NaN,NaN,NaN,58.358,-137.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3487,"Algeria: Algiers, 2014",NaN,NaN,NaN,NaN,NaN,36.851,3.161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3488,"China: Yunnan Province: Yongshan, 2014",NaN,NaN,NaN,NaN,NaN,28.182,103.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3489,"Iran: Abdanan, 2014",NaN,NaN,NaN,NaN,NaN,32.739,47.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3490,"Philippines: Barangay Luayon, 2014",NaN,NaN,NaN,NaN,NaN,6.881,125.251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3491,"Chile: Easter Island Region, 2014",NaN,NaN,NaN,NaN,NaN,-32.115,-110.779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3492,"Indonesia: N. Moluccas Islands, 2014",NaN,NaN,NaN,NaN,NaN,1.928,126.547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3493,"Japan: Nagano: Hakuba, Otari, 2014",NaN,NaN,NaN,NaN,NaN,36.64,137.911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3494,"Japan: Honshu, 2015",NaN,NaN,NaN,NaN,NaN,39.83,142.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3495,"China: Yunnan Province, 2015",NaN,NaN,NaN,NaN,NaN,23.663,102.907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3496,"China: Xinjiang Province: Shawan, 2015",NaN,NaN,NaN,NaN,NaN,44.107,85.641,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3497,"Balkans Nw: Serbia: Kosjeric, 2015",NaN,NaN,NaN,NaN,NaN,44.126,19.936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3498,"Papua New Guinea, 2015",NaN,NaN,NaN,NaN,NaN,-4.76,152.556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3499,"Japan: Honshu: S. Of, 2015",NaN,NaN,NaN,NaN,NaN,31.594,140.167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3500,"Papua New Guinea, 2015",NaN,NaN,NaN,NaN,NaN,-5.465,151.886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3501,"Japan: Bonin Islands [Chichijima Island], 2015",NaN,NaN,NaN,NaN,NaN,27.831,140.493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df1 = pd.read_csv('../datasets/2014_world_gdp_with_codes.csv')
df1

                    COUNTRY  GDP (BILLIONS) CODE
0               Afghanistan           21.71  AFG
1                   Albania           13.40  ALB
2                   Algeria          227.80  DZA
3            American Samoa            0.75  ASM
4                   Andorra            4.80  AND
5                    Angola          131.40  AGO
6                  Anguilla            0.18  AIA
7       Antigua and Barbuda            1.24  ATG
8                 Argentina          536.20  ARG
9                   Armenia           10.88  ARM
10                    Aruba            2.52  ABW
11                Australia         1483.00  AUS
12                  Austria          436.10  AUT
13               Azerbaijan           77.91  AZE
14             Bahamas, The            8.65  BHM
15                  Bahrain           34.05  BHR
16               Bangladesh          186.60  BGD
17                 Barbados            4.28  BRB
18                  Belarus           75.25  BLR
19                  Belgium          527.80  BEL
20                   Belize            1.67  BLZ
21                    Benin            9.24  BEN
22                  Bermuda            5.20  BMU
23                   Bhutan            2.09  BTN
24                  Bolivia           34.08  BOL
25   Bosnia and Herzegovina           19.55  BIH
26                 Botswana           16.30  BWA
27                   Brazil         2244.00  BRA
28   British Virgin Islands            1.10  VGB
29                   Brunei           17.43  BRN
..                      ...             ...  ...
192                  Sweden          559.10  SWE
193             Switzerland          679.00  CHE
194                   Syria           64.70  SYR
195                  Taiwan          529.50  TWN
196              Tajikistan            9.16  TJK
197                Tanzania           36.62  TZA
198                Thailand          373.80  THA
199             Timor-Leste            4.51  TLS
200                    Togo            4.84  TGO
201                   Tonga            0.49  TON
202     Trinidad and Tobago           29.63  TTO
203                 Tunisia           49.12  TUN
204                  Turkey          813.30  TUR
205            Turkmenistan           43.50  TKM
206                  Tuvalu            0.04  TUV
207                  Uganda           26.09  UGA
208                 Ukraine          134.90  UKR
209    United Arab Emirates          416.40  ARE
210          United Kingdom         2848.00  GBR
211           United States        17420.00  USA
212                 Uruguay           55.60  URY
213              Uzbekistan           63.08  UZB
214                 Vanuatu            0.82  VUT
215               Venezuela          209.20  VEN
216                 Vietnam          187.80  VNM
217          Virgin Islands            5.08  VGB
218               West Bank            6.64  WBG
219                   Yemen           45.45  YEM
220                  Zambia           25.61  ZMB
221                Zimbabwe           13.74  ZWE

[222 rows x 3 columns]

In [46]:
df2 = pd.read_csv('../datasets/migrants.csv')
df2

,Unnamed: 0,ccode,country,number1000,percentarea,under18
0,0,AFG,Afghanistan,134,0.0,40
1,1,ALB,Albania,52,2.0,47
2,2,DZA,Algeria,249,1.0,20
3,3,AND,Andorra,41,53.0,7
4,4,AGO,Angola,638,2.0,47
5,5,AIA,Anguilla,6,37.0,22
6,6,ATG,Antigua and Barbuda,29,28.0,11
7,7,ARG,Argentina,2165,5.0,8
8,8,ARM,Armenia,191,7.0,8
9,9,AUS,Australia,7036,29.0,7
10,10,AUT,Austria,1660,19.0,5
11,11,AZE,Azerbaijan,259,3.0,11
12,12,BHS,Bahamas,62,16.0,12
13,13,BHR,Bahrain,723,48.0,14
14,14,BGD,Bangladesh,1501,1.0,18
15,15,BRB,Barbados,35,12.0,14
16,16,BLR,Belarus,1079,11.0,3
17,17,BEL,Belgium,1268,11.0,18
18,18,BLZ,Belize,60,16.0,11
19,19,BEN,Benin,253,2.0,26
20,20,BTN,Bhutan,52,6.0,11
21,21,BOL,Bolivia (Plurinational State of),149,1.0,32
22,22,BIH,Bosnia and Herzegovina,37,1.0,17
23,23,BWA,Botswana,166,7.0,23
24,24,BRA,Brazil,736,0.0,14
25,25,BRN,Brunei Darussalam,109,25.0,17
26,26,BGR,Bulgaria,154,2.0,31
27,27,BFA,Burkina Faso,709,4.0,21
28,28,BDI,Burundi,300,3.0,28
29,29,CPV,Cabo Verde,15,3.0,10
...,...,...,...,...,...,...
167,167,SDN,Sudan,736,2.0,31
168,168,SUR,Suriname,48,8.0,30
169,169,SWE,Sweden,1748,18.0,10
170,170,CHE,Switzerland,2506,30.0,6
171,171,SYR,Syrian Arab Republic,1014,6.0,17
172,172,TJK,Tajikistan,273,3.0,6
173,173,THA,Thailand,3589,5.0,14
174,174,MKD,The former Yugoslav Republic of Macedonia,131,6.0,14
175,175,TLS,Timor-Leste,12,1.0,18
176,176,TGO,Togo,284,4.0,39
177,177,TON,Tonga,5,5.0,28
178,178,TTO,Trinidad and Tobago,50,4.0,17
179,179,TUN,Tunisia,58,1.0,17
180,180,TUR,Turkey,4882,6.0,26
181,181,TKM,Turkmenistan,195,3.0,7
182,182,TUV,Tuvalu,0,1.0,20
183,183,UGA,Uganda,1692,4.0,27
184,184,UKR,Ukraine,4964,11.0,5
185,185,ARE,United Arab Emirates,8313,88.0,14
186,186,GBR,United Kingdom of Great Britain and Northern I...,8842,13.0,8
187,187,TZA,United Republic of Tanzania,493,1.0,21
188,188,USA,United States of America,49777,15.0,5
189,189,URY,Uruguay,80,2.0,19
190,190,UZB,Uzbekistan,1159,4.0,8
191,191,VUT,Vanuatu,3,1.0,24
192,192,VEN,Venezuela (Bolivarian Republic of),1426,4.0,14
193,193,VNM,Viet Nam,76,0.0,15
194,194,YEM,Yemen,384,1.0,30
195,195,ZMB,Zambia,157,1.0,18
196,196,ZWE,Zimbabwe,404,2.0,13

In [ ]:
#merge

In [70]:
df = pd.read_csv('../datasets/maternal_health.csv')
df

,Unnamed: 0,ccode,country,year,Total,age 15-17,age 18-19,<20,>20,age 20-34,age 35-49
0,0,AFG,Afghanistan,2010.0,47.872012,48.292231,45.121149,45.634003,46.635823,46.702356,46.323971
1,1,ALB,Albania,2000.0,95.269887,100.000000,100.000000,100.000000,94.967483,95.399258,91.427947
2,2,ALB,Albania,2005.0,97.124568,100.000000,100.000000,100.000000,96.828206,97.107991,94.331780
3,3,ALB,Albania,2008.0,98.420840,92.577894,100.000000,97.778378,98.465574,98.467706,98.438906
4,4,ARG,Argentina,2012.0,98.070102,99.298196,98.597808,98.905995,97.936854,97.992949,97.707396
5,5,ARM,Armenia,2000.0,92.101195,96.109264,87.972606,89.350448,92.591964,93.205895,83.879760
6,6,ARM,Armenia,2005.0,93.839665,86.769271,92.942678,92.429901,93.998695,94.230843,89.852780
7,7,ARM,Armenia,2010.0,99.035387,100.000000,100.000000,100.000000,98.944143,98.868247,100.000000
8,8,AZE,Azerbaijan,2000.0,68.671679,78.571429,72.222222,74.000000,68.128655,69.085174,56.000000
9,9,AZE,Azerbaijan,2006.0,79.996051,68.898087,80.001614,77.059327,80.264022,81.196719,69.278306
10,10,BGD,Bangladesh,2004.0,43.135359,42.611932,42.753976,42.677188,43.360755,43.909246,36.876525
11,11,BGD,Bangladesh,2006.0,47.664123,43.198118,51.278507,47.317292,47.792671,48.901732,35.224971
12,12,BGD,Bangladesh,2007.0,53.691334,53.566186,56.142853,54.818789,53.146503,54.429514,35.629927
13,13,BGD,Bangladesh,2011.0,55.148640,55.648183,59.862869,57.827936,53.989718,54.730675,40.107119
14,14,BGD,Bangladesh,2013.0,58.665836,61.234322,61.819273,61.636676,57.943678,59.447698,43.044779
15,15,BGD,Bangladesh,2014.0,64.848641,63.707862,65.953797,64.839768,64.852772,65.009907,61.947065
16,16,BRB,Barbados,2012.0,93.427565,0.000000,100.000000,100.000000,93.561312,91.056967,100.000000
17,17,BLR,Belarus,2005.0,99.431960,100.000000,98.951731,99.125469,99.462047,99.410346,100.000000
18,18,BLR,Belarus,2012.0,99.646007,80.784083,100.000000,95.128998,99.894453,99.884760,100.000000
19,19,BLZ,Belize,2006.0,93.993803,100.000000,90.761084,94.032856,94.324536,95.304957,88.385052
20,20,BLZ,Belize,2011.0,96.221169,97.601453,96.051111,96.664816,96.129316,96.972399,90.820817
21,21,BEN,Benin,2001.0,87.492314,84.603933,86.914611,86.112041,87.699992,88.412138,83.903677
22,22,BEN,Benin,2006.0,87.894488,84.066875,85.722449,85.167841,88.244939,88.863761,84.568013
23,23,BEN,Benin,2011.0,86.476201,82.180555,85.160407,84.098556,86.754114,87.167658,84.469249
24,24,BTN,Bhutan,2010.0,97.298702,89.495792,92.053030,91.854342,97.532213,98.133831,94.399152
25,25,BOL,Bolivia (Plurinational State of),2000.0,82.620205,88.458966,92.248763,90.911268,81.063599,84.493126,65.602663
26,26,BOL,Bolivia (Plurinational State of),2003.0,78.626215,79.652582,83.726669,81.917612,78.015069,80.725507,67.354215
27,27,BOL,Bolivia (Plurinational State of),2008.0,90.941679,85.787658,90.958979,88.460044,91.426100,92.543842,86.606151
28,28,BIH,Bosnia and Herzegovina,2000.0,99.175258,100.000000,100.000000,100.000000,99.099099,99.012346,100.000000
29,29,BIH,Bosnia and Herzegovina,2006.0,98.897536,93.333333,100.000000,99.079579,98.882085,98.779868,100.000000
...,...,...,...,...,...,...,...,...,...,...,...
237,237,UKR,Ukraine,2012.0,98.646377,95.295790,98.622783,97.834679,98.702743,98.861797,97.199362
238,238,URY,Uruguay,2012.0,97.203461,81.129211,98.882569,97.195832,97.206910,97.151445,97.589774
239,239,UZB,Uzbekistan,2000.0,96.501458,100.000000,94.545455,94.915254,96.650718,96.943973,92.105263
240,240,UZB,Uzbekistan,2006.0,99.013377,100.000000,99.411943,99.453904,98.987978,99.101673,97.216151
241,241,VUT,Vanuatu,2006.0,84.300028,76.462217,88.686721,84.744865,84.241750,85.635942,75.817700
242,242,VEN,Venezuela (Bolivarian Republic of),2000.0,94.140168,95.001609,87.743419,90.867660,94.645998,93.912909,100.000000
243,243,VNM,Viet Nam,2000.0,68.339092,36.276846,64.355944,58.724093,69.283931,68.870574,71.741392
244,244,VNM,Viet Nam,2002.0,87.891157,57.495571,83.326543,79.440230,88.648739,89.637047,78.677670
245,245,VNM,Viet Nam,2006.0,90.772913,78.884332,84.647552,83.234128,91.587629,91.760867,90.254077
246,246,VNM,Viet Nam,2010.0,93.732194,0.000000,54.518356,54.518356,92.278466,92.099868,93.384326
247,247,VNM,Viet Nam,2013.0,95.795875,92.642918,89.892593,90.685095,96.268480,96.364500,95.357331
248,248,YEM,Yemen,2006.0,47.015403,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
249,249,YEM,Yemen,2013.0,59.446191,62.577868,65.424824,64.598098,58.686291,60.775550,48.689872
250,250,ZMB,Zambia,2001.0,92.094307,93.553012,91.545139,92.329807,92.034117,92.777007,88.112935
251,251,ZMB,Zambia,2007.0,92.752721,94.045016,94.417693,94.268669,92.463598,93.272123,88.341981
252,252,ZMB,Zambia,2013.0,95.435860,96.838184,94.712581,95.561380,95.407036,95.867828,93.356740
253,253,ZWE,Zimbabwe,2005.0,93.527057,90.794256,93.609765,92.621212,93.739904,94.234769,89.807006
254,254,ZWE,Zimbabwe,2009.0,88.438744,89.586918,89.718127,89.670174,88.144729,88.939129,81.515961
255,255,ZWE,Zimbabwe,2010.0,87.221648,82.240235,85.095599,84.030901,87.914199,88.162136,86.175946
256,256,ZWE,Zimbabwe,2014.0,93.684247,93.429230,93.129798,93.247561,93.780901,93.843905,93.404956
257,257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,258,Definition:,Percentage of women aged 15–49 years attended ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,259,NaN,The indicator refers to women who had a live b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,261,Note:,Database include reanalyzed data from DHS and ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,262,NaN,Includes surveys which microdata were availabl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,264,Source:,"UNICEF global databases 2016 based on DHS, MICS .",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,266,Contact us:,data@unicef.org,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
df = pd.read_csv('../datasets/gapminderDataFiveYear.csv')
df
#group

          country  year         pop continent  lifeExp    gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801   779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332   820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997   853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020   836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088   739.981106
5     Afghanistan  1977  14880372.0      Asia   38.438   786.113360
6     Afghanistan  1982  12881816.0      Asia   39.854   978.011439
7     Afghanistan  1987  13867957.0      Asia   40.822   852.395945
8     Afghanistan  1992  16317921.0      Asia   41.674   649.341395
9     Afghanistan  1997  22227415.0      Asia   41.763   635.341351
10    Afghanistan  2002  25268405.0      Asia   42.129   726.734055
11    Afghanistan  2007  31889923.0      Asia   43.828   974.580338
12        Albania  1952   1282697.0    Europe   55.230  1601.056136
13        Albania  1957   1476505.0    Europe   59.280  1942.284244
14        Albania  1962   1728137.0    Europe   64.820  2312.888958
15        Albania  1967   1984060.0    Europe   66.220  2760.196931
16        Albania  1972   2263554.0    Europe   67.690  3313.422188
17        Albania  1977   2509048.0    Europe   68.930  3533.003910
18        Albania  1982   2780097.0    Europe   70.420  3630.880722
19        Albania  1987   3075321.0    Europe   72.000  3738.932735
20        Albania  1992   3326498.0    Europe   71.581  2497.437901
21        Albania  1997   3428038.0    Europe   72.950  3193.054604
22        Albania  2002   3508512.0    Europe   75.651  4604.211737
23        Albania  2007   3600523.0    Europe   76.423  5937.029526
24        Algeria  1952   9279525.0    Africa   43.077  2449.008185
25        Algeria  1957  10270856.0    Africa   45.685  3013.976023
26        Algeria  1962  11000948.0    Africa   48.303  2550.816880
27        Algeria  1967  12760499.0    Africa   51.407  3246.991771
28        Algeria  1972  14760787.0    Africa   54.518  4182.663766
29        Algeria  1977  17152804.0    Africa   58.014  4910.416756
...           ...   ...         ...       ...      ...          ...
1674  Yemen, Rep.  1982   9657618.0      Asia   49.113  1977.557010
1675  Yemen, Rep.  1987  11219340.0      Asia   52.922  1971.741538
1676  Yemen, Rep.  1992  13367997.0      Asia   55.599  1879.496673
1677  Yemen, Rep.  1997  15826497.0      Asia   58.020  2117.484526
1678  Yemen, Rep.  2002  18701257.0      Asia   60.308  2234.820827
1679  Yemen, Rep.  2007  22211743.0      Asia   62.698  2280.769906
1680       Zambia  1952   2672000.0    Africa   42.038  1147.388831
1681       Zambia  1957   3016000.0    Africa   44.077  1311.956766
1682       Zambia  1962   3421000.0    Africa   46.023  1452.725766
1683       Zambia  1967   3900000.0    Africa   47.768  1777.077318
1684       Zambia  1972   4506497.0    Africa   50.107  1773.498265
1685       Zambia  1977   5216550.0    Africa   51.386  1588.688299
1686       Zambia  1982   6100407.0    Africa   51.821  1408.678565
1687       Zambia  1987   7272406.0    Africa   50.821  1213.315116
1688       Zambia  1992   8381163.0    Africa   46.100  1210.884633
1689       Zambia  1997   9417789.0    Africa   40.238  1071.353818
1690       Zambia  2002  10595811.0    Africa   39.193  1071.613938
1691       Zambia  2007  11746035.0    Africa   42.384  1271.211593
1692     Zimbabwe  1952   3080907.0    Africa   48.451   406.884115
1693     Zimbabwe  1957   3646340.0    Africa   50.469   518.764268
1694     Zimbabwe  1962   4277736.0    Africa   52.358   527.272182
1695     Zimbabwe  1967   4995432.0    Africa   53.995   569.795071
1696     Zimbabwe  1972   5861135.0    Africa   55.635   799.362176
1697     Zimbabwe  1977   6642107.0    Africa   57.674   685.587682
1698     Zimbabwe  1982   7636524.0    Africa   60.363   788.855041
1699     Zimbabwe  1987   9216418.0    Africa   62.351   706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377   693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809   792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989   672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487   469.709298

[1704 rows x 6 columns]

In [71]:
df = pd.read_csv('../datasets/disease.csv')
df
#discribe, pie

,Unnamed: 0,ccode,country,year,AIDS,Congenital,Diarrhoea,Injury,Intrapartum,Malaria,Measles,Meningitis,Pneumonia,Preterm,Sepsis,Tetanus,Other,Total
0,0,AFG,Afghanistan,2017,0.0,6.4,7.8,5.8,15.9,0.1,1.8,3.4,14.9,19.2,8.4,1.6,14.7,100
1,1,ALB,Albania,2017,0.7,27.2,0.6,7.0,8.8,0.0,0.0,2.2,8.9,28.9,2.6,0.8,12.3,100
2,2,DZA,Algeria,2017,0.1,16.0,4.8,6.3,14.4,0.0,0.3,1.0,13.0,21.1,9.2,0.2,13.7,100
3,3,AND,Andorra,2017,0.0,16.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,66.7,0.0,0.0,16.7,100
4,4,AGO,Angola,2017,2.8,7.0,9.3,6.4,13.6,7.0,0.7,2.0,17.3,12.0,5.7,0.5,15.9,100
5,5,ATG,Antigua and Barbuda,2017,0.0,26.7,0.0,1.0,7.0,0.0,0.0,0.0,6.6,17.0,1.9,0.0,39.8,100
6,6,ARG,Argentina,2017,0.1,29.3,1.1,6.5,4.6,0.0,0.0,1.1,6.5,28.1,5.4,0.0,17.3,100
7,7,ARM,Armenia,2017,0.0,26.6,1.3,9.0,6.7,0.0,0.0,1.6,10.7,24.4,3.6,0.0,16.2,100
8,8,AUS,Australia,2017,0.0,27.1,0.6,6.8,11.1,0.0,0.0,0.7,3.0,21.5,1.3,0.0,27.9,100
9,9,AUT,Austria,2017,0.0,36.0,0.0,5.0,9.7,0.0,0.0,1.1,2.6,15.4,3.3,0.0,26.8,100
10,10,AZE,Azerbaijan,2017,0.1,13.9,6.8,8.3,12.8,0.0,0.0,1.3,12.7,20.3,5.5,0.2,18.2,100
11,11,BHS,Bahamas,2017,1.5,18.1,3.4,5.1,9.5,0.0,0.0,0.0,14.2,25.1,3.5,0.0,19.6,100
12,12,BHR,Bahrain,2017,0.3,35.5,0.3,4.4,2.9,0.0,0.0,0.9,1.9,34.9,0.2,0.0,18.9,100
13,13,BGD,Bangladesh,2017,0.0,9.1,7.4,7.9,13.8,0.0,1.9,1.1,13.5,18.0,11.0,0.2,15.9,100
14,14,BRB,Barbados,2017,0.0,25.3,0.0,7.3,13.4,0.0,0.0,0.0,2.4,16.0,10.7,0.0,24.8,100
15,15,BLR,Belarus,2017,3.3,33.9,0.6,8.0,7.1,0.0,0.0,1.2,5.7,19.1,1.9,0.0,19.3,100
16,16,BEL,Belgium,2017,0.0,29.3,0.3,7.2,10.0,0.0,0.0,1.6,3.4,17.3,2.5,0.0,28.4,100
17,17,BLZ,Belize,2017,0.7,22.2,3.9,7.9,9.6,0.0,0.0,0.3,5.0,22.1,6.2,0.0,22.0,100
18,18,BEN,Benin,2017,0.9,5.0,9.5,5.2,10.3,16.4,0.6,2.3,13.8,12.8,6.9,0.3,15.9,100
19,19,BTN,Bhutan,2017,1.1,11.0,6.0,7.6,13.1,0.0,0.5,1.8,14.6,20.2,9.1,0.2,14.8,100
20,20,BOL,Bolivia (Plurinational State of),2017,0.1,14.6,5.9,7.5,14.7,0.0,0.0,1.0,13.0,19.0,7.4,0.3,16.5,100
21,21,BIH,Bosnia and Herzegovina,2017,0.0,32.0,0.7,4.2,8.8,0.0,1.6,1.2,5.9,30.1,3.6,0.0,11.9,100
22,22,BWA,Botswana,2017,7.7,11.7,3.7,4.1,15.9,0.1,0.0,0.7,9.1,26.4,9.2,0.4,11.1,100
23,23,BRA,Brazil,2017,0.1,23.4,2.1,5.9,9.5,0.0,0.0,1.0,7.9,18.7,7.9,0.0,23.4,100
24,24,BRN,Brunei Darussalam,2017,0.0,28.8,3.0,1.5,5.2,0.0,0.0,0.0,4.0,18.9,6.1,0.0,32.6,100
25,25,BGR,Bulgaria,2017,0.1,24.3,1.8,5.9,9.0,0.0,0.0,1.4,14.2,28.2,2.0,0.0,13.1,100
26,26,BFA,Burkina Faso,2017,0.4,4.6,8.0,6.2,10.2,20.0,0.9,2.4,13.3,10.8,6.7,0.2,16.2,100
27,27,BDI,Burundi,2017,0.9,5.8,8.0,7.6,12.5,9.7,0.1,2.3,14.9,12.4,5.8,0.3,19.7,100
28,28,CPV,Cabo Verde,2017,1.0,22.4,3.6,5.0,9.7,0.0,0.0,1.1,11.6,23.3,5.9,0.4,16.0,100
29,29,KHM,Cambodia,2017,0.1,10.1,7.4,8.8,13.0,0.8,0.2,1.4,14.2,17.5,8.2,0.2,18.1,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,358,SDN,Sudan,2000,0.1,3.9,14.7,5.1,11.0,1.9,4.0,5.5,21.6,13.2,5.3,1.0,12.6,100
359,359,SUR,Suriname,2000,1.3,12.2,6.9,8.6,7.8,1.6,0.0,2.2,8.4,20.7,14.5,0.0,15.7,100
360,360,SWE,Sweden,2000,0.0,45.0,0.0,4.0,9.2,0.0,0.0,1.2,1.8,16.7,5.1,0.0,17.0,100
361,361,CHE,Switzerland,2000,0.0,30.7,0.4,8.2,8.0,0.0,0.0,2.2,1.5,25.8,2.6,0.0,20.6,100
362,362,SYR,Syrian Arab Republic,2000,0.3,20.2,9.8,3.4,11.3,0.0,0.1,1.3,14.8,22.3,4.4,0.6,11.4,100
363,363,TJK,Tajikistan,2000,0.0,5.6,15.2,6.2,10.2,0.0,0.0,5.4,22.7,13.8,3.1,0.5,17.3,100
364,364,THA,Thailand,2000,10.1,18.9,4.3,4.5,8.0,0.7,0.2,1.2,12.1,22.8,5.3,0.4,11.3,100
365,365,MKD,The former Yugoslav Republic of Macedonia,2000,0.0,16.7,8.7,2.9,11.0,0.0,0.0,0.9,8.1,35.6,2.3,0.0,13.8,100
366,366,TLS,Timor-Leste,2000,0.0,4.0,17.4,6.1,11.8,1.5,0.0,3.9,24.9,10.4,5.2,1.4,13.4,100
367,367,TGO,Togo,2000,5.0,2.9,8.7,2.7,9.2,23.0,10.0,2.7,12.5,10.5,4.3,0.7,7.8,100
368,368,TON,Tonga,2000,0.0,23.2,5.4,8.8,6.1,0.0,0.0,2.4,14.1,20.4,4.0,0.0,15.7,100
369,369,TTO,Trinidad and Tobago,2000,3.1,12.6,1.0,2.5,26.3,0.0,0.0,1.2,3.2,37.3,2.8,0.0,9.8,100
370,370,TUN,Tunisia,2000,0.0,17.9,5.4,5.1,11.2,0.0,0.0,1.5,15.7,23.5,3.4,1.3,15.0,100
371,371,TUR,Turkey,2000,0.0,30.6,1.9,3.8,5.5,0.0,0.0,0.6,6.8,22.6,3.5,0.0,24.8,100
372,372,TKM,Turkmenistan,2000,0.1,7.6,13.8,5.9,11.0,0.0,0.0,3.7,20.9,16.2,3.2,0.4,17.1,100
373,373,TUV,Tuvalu,2000,0.0,13.2,5.1,5.8,12.2,0.0,0.0,1.4,17.6,28.8,5.8,0.0,10.2,100
374,374,UGA,Uganda,2000,6.3,2.9,11.4,3.1,7.2,24.4,6.9,3.4,14.9,7.2,2.9,0.4,9.1,100
375,375,UKR,Ukraine,2000,4.6,22.2,2.2,6.8,7.7,0.0,0.2,2.1,14.8,24.9,3.6,0.0,10.8,100
376,376,ARE,United Arab Emirates,2000,0.3,27.2,0.7,8.0,8.7,0.0,0.0,1.6,5.4,22.7,2.4,0.0,22.9,100
377,377,GBR,United Kingdom,2000,0.1,23.7,1.3,5.0,6.2,0.0,0.0,3.0,4.1,34.9,2.7,0.0,19.0,100
378,378,TZA,United Republic of Tanzania,2000,9.3,3.4,13.3,3.9,9.7,12.3,2.0,3.8,18.1,8.5,4.1,0.5,11.2,100
379,379,USA,United States,2000,0.1,25.3,1.9,11.3,4.8,0.0,0.0,0.9,3.1,27.6,2.7,0.0,22.2,100
380,380,URY,Uruguay,2000,0.4,26.0,3.2,7.5,7.2,0.0,0.0,1.3,9.0,21.4,6.3,0.0,17.5,100
381,381,UZB,Uzbekistan,2000,0.2,9.1,11.1,5.4,12.5,0.0,0.0,3.8,18.7,18.9,4.0,0.5,15.8,100
382,382,VUT,Vanuatu,2000,0.0,14.9,16.8,4.5,8.7,7.6,0.0,1.7,17.8,17.8,2.8,0.6,6.9,100
383,383,VEN,Venezuela (Bolivarian Republic of),2000,0.2,15.0,11.6,7.2,8.2,0.0,0.0,2.1,8.6,23.1,8.8,0.0,15.1,100
384,384,VNM,Viet Nam,2000,0.4,16.0,12.4,3.5,7.7,0.2,6.7,1.6,17.9,20.4,3.9,0.4,8.8,100
385,385,YEM,Yemen,2000,0.0,3.9,14.6,5.5,10.1,0.6,5.6,3.1,22.0,14.5,6.1,1.5,12.5,100
386,386,ZMB,Zambia,2000,14.1,3.2,14.2,3.3,8.3,9.4,4.9,3.3,17.0,7.5,3.5,0.4,10.7,100
387,387,ZWE,Zimbabwe,2000,39.3,3.7,7.2,2.6,9.0,2.5,0.3,1.9,11.2,10.5,3.5,0.3,8.0,100

In [69]:
df = pd.read_csv('../datasets/su5m.csv')
df.mean()

Unnamed: 0    97.000000
m1990         76.001026
m2000         60.231282
m2010         41.063590
m2015         33.532308
m2017         31.383077
f1990         67.412821
f2000         53.001026
f2010         35.527692
f2015         28.628205
f2017         26.704615
dtype: float64