In [1]:
%matplotlib inline

import zipfile
import numpy as np
import pylab as plt
import pandas as pd

from glob import glob

In [3]:
zip_ref = zipfile.ZipFile('../../S04/datasets/UN.zip', 'r')
zip_ref.extractall('../../S04/datasets/')

In [4]:
glob('../../S04/datasets/*')

['../../S04/datasets/UN_cleaned.csv',
 '../../S04/datasets/UN.zip',
 '../../S04/datasets/south-park-dialogue.zip',
 '../../S04/datasets/UN',
 '../../S04/datasets/worldbank.zip',
 '../../S04/datasets/exercise.npy']

In [5]:
countries = ['Afghanistan', 'Albania',
       'Algeria', 'Andorra', 'Angola', 'Anguilla', 'Antigua and Barbuda',
       'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia (Plurin. State of)', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'British Virgin Islands', 'Brunei Darussalam',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Canada', 'Cayman Islands', 'Central African Republic',
       'Chad', 'Chile', 'China', 'China, Hong Kong SAR',
       'China, Macao SAR', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', 'Croatia', 'Cuba',
       'Cyprus', 'Czechia', "Dem. People's Rep. Korea",
       'Dem. Rep. of the Congo', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia',
       'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland',
       'France', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran (Islamic Republic of)', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Dem. Rep.", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico',
       'Micronesia (Fed. States of)', 'Monaco', 'Mongolia', 'Montenegro',
       'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles [former]',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'North Macedonia', 'Norway', 'Oman',
       'Other non-specified areas', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'RÃ©union', 'Romania', 'Russian Federation',
       'Rwanda', 'Saint Helena', 'Ascension', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent & Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'State of Palestine', 'Sudan', 'Suriname',
       'Eswatini', 'Sweden', 'Switzerland', 'Syrian Arab Republic',
       'Tajikistan', 'Thailand', 'Timor-Leste', 'Togo', 'Tokelau',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom',
       'United Rep. of Tanzania', 'United States of America',
       'United States Virgin Islands', 'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Boliv. Rep. of)', 'Viet Nam',
       'Wallis and Futuna Islands', 'Yemen', 'Zambia', 'Zimbabwe']

### Internet

In [6]:
filename = '../datasets/UN/SYB62_T29_201904_Internet Usage.csv'
df = pd.read_csv(filename,encoding='latin1',header=[1])
df = df.rename(columns={'Unnamed: 1':'country','Value':'internetusage'})
df = df[df['country'].isin(countries)]
df.columns

Index(['Region/Country/Area', 'country', 'Year', 'Series', 'internetusage',
       'Footnotes', 'Source'],
      dtype='object')

In [7]:
df_internet = df[['country', 'Year', 'internetusage']]
del df

### CPI

In [8]:
filename = '../datasets/UN/SYB61_T19_Consumer Price Index.csv'
df = pd.read_csv(filename,encoding='latin1',header=[1])
df = df.rename(columns={'Unnamed: 1':'country'})
df = df[df['country'].isin(countries)]
df.columns

Index(['Region/Country/Area', 'country', 'Year', 'Series', 'Value',
       'Footnotes', 'Source'],
      dtype='object')

In [9]:
dfp = df[['country', 'Year', 'Series', 'Value']]
dfp1 = dfp[dfp['Series']=='Consumer price index: General']
dfp1 = dfp1.rename(columns={'Value':'CPIG'})
dfp1 = dfp1[['country', 'Year', 'CPIG']]

dfp2 = dfp[dfp['Series']=='Consumer price index: Food']
dfp2 = dfp2.rename(columns={'Value':'CPIF'})
dfp2 = dfp2[['country', 'Year', 'CPIF']]

dfcpi = dfp1.merge(dfp2,on=['country', 'Year'])
del df,dfp,dfp1,dfp2

### Imports and Exports

In [10]:
filename = '../datasets/UN/SYB61_T21_Total Imports, Exports and Balance of Trade.csv'
df = pd.read_csv(filename,encoding='latin1',header=[1])
df = df.rename(columns={'Unnamed: 1':'country'})
df = df[df['country'].isin(countries)]
df.columns

Index(['Region/Country/Area', 'country', 'Year', 'Series', 'System of trade',
       'System of trade footnote', 'Value', 'Footnotes', 'Source'],
      dtype='object')

In [11]:
dfp = df[['country', 'Year', 'Series', 'Value']]
dfp1 = dfp[dfp['Series']=='Imports CIF (millions of US dollars)']
dfp1 = dfp1.rename(columns={'Value':'Imports'})
dfp1 = dfp1[['country', 'Year', 'Imports']]

dfp2 = dfp[dfp['Series']=='Exports FOB (millions of US dollars)']
dfp2 = dfp2.rename(columns={'Value':'Exports'})
dfp2 = dfp2[['country', 'Year', 'Exports']]
dfcpi
dfimex = dfp1.merge(dfp2,on=['country', 'Year'])
del df,dfp,dfp1,dfp2

### Crime

In [12]:
filename = '../datasets/UN/SYB62_T12_201904_Intentional homicides and Other Crimes.csv'
df = pd.read_csv(filename,encoding='latin1',header=[1])
df = df.rename(columns={'Unnamed: 1':'country'})
df = df[df['country'].isin(countries)]
df.columns

Index(['Region/Country/Area', 'country', 'Year', 'Series', 'Value',
       'Footnotes', 'Source'],
      dtype='object')

In [13]:
df = df[df['Series']=='Intentional homicide rates per 100,000']
df = df.rename(columns={'Value':'homicide'})
dfcrime = df[['country', 'Year', 'homicide']]
del df

### Migrants and Refugees

In [14]:
filename = '../datasets/UN/SYB61_T04_International Migrants and Refugees.csv'
df = pd.read_csv(filename,encoding='latin1',header=[1])
df = df.rename(columns={'Unnamed: 1':'country'})
df = df[df['country'].isin(countries)]
df.columns

Index(['Region/Country/Area', 'country', 'Year', 'Series', 'Value',
       'Footnotes', 'Source'],
      dtype='object')

In [15]:
df = df[df['Series']=='International migrant stock: Both sexes (% total population)']
df = df.rename(columns={'Value':'migrants'})
dfmig = df[['country', 'Year', 'migrants']]
del df

### GDP and GDP Per Capita

In [16]:
filename = '../datasets/UN/SYB62_T13_201904_GDP and GDP Per Capita.csv'
df = pd.read_csv(filename,encoding='latin1',header=[1])
df = df.rename(columns={'Unnamed: 1':'country'})
df = df[df['country'].isin(countries)]
df.columns

Index(['Region/Country/Area', 'country', 'Year', 'Series', 'Value',
       'Footnotes', 'Source'],
      dtype='object')

In [17]:
dfp = df[['country', 'Year', 'Series', 'Value']]
dfp1 = dfp[dfp['Series']=='GDP in current prices (millions of US dollars)']
dfp1 = dfp1.rename(columns={'Value':'GDP'})
dfp1 = dfp1[['country', 'Year', 'GDP']]

dfp2 = dfp[dfp['Series']=='GDP per capita (US dollars)']
dfp2 = dfp2.rename(columns={'Value':'PPP'})
dfp2 = dfp2[['country', 'Year', 'PPP']]

dfgdp = dfp1.merge(dfp2,on=['country', 'Year'])
del df,dfp,dfp1,dfp2

### Tourist-Visitors Arrival and Expenditure

In [18]:
filename = '../datasets/UN/SYB62_T30_201904_Tourist-Visitors Arrival and Expenditure.csv'
df = pd.read_csv(filename,encoding='latin1',header=[1])
df = df.rename(columns={'Unnamed: 1':'country'})
df = df[df['country'].isin(countries)]
df.columns

Index(['Region/Country/Area', 'country', 'Year', 'Series',
       'Tourism arrivals series type', 'Tourism arrivals series type footnote',
       'Value', 'Footnotes', 'Source'],
      dtype='object')

In [19]:
dfp = df[['country', 'Year', 'Series', 'Value']]
dfp1 = dfp[dfp['Series']=='Tourism expenditure (millions of US dollars)']
dfp1 = dfp1.rename(columns={'Value':'tourexp'})
dfp1 = dfp1[['country', 'Year', 'tourexp']]

dfp2 = dfp[dfp['Series']=='Tourist/visitor arrivals (thousands)']
dfp2 = dfp2.rename(columns={'Value':'tvarrival'})
dfp2 = dfp2[['country', 'Year', 'tvarrival']]

dftour = dfp1.merge(dfp2,on=['country', 'Year'])
del df,dfp,dfp1,dfp2

### Public Expenditure on Education

In [20]:
filename = '../datasets/UN/SYB62_T09_201905_Public Expenditure on Education.csv'
df = pd.read_csv(filename,encoding='latin1',header=[1])
df = df.rename(columns={'Unnamed: 1':'country'})
df = df[df['country'].isin(countries)]
df.columns

Index(['Region/Country/Area', 'country', 'Year', 'Series', 'Value',
       'Footnotes', 'Source'],
      dtype='object')

In [21]:
df = df[df['Series']=='Public expenditure on education (% of government expenditure)']
df = df.rename(columns={'Value':'education'})
dfedu = df[['country', 'Year', 'education']]
del df

### Index of industrial production

In [22]:
filename = '../datasets/UN/SYB58_T25 Index of industrial production.csv'
df = pd.read_csv(filename,encoding='latin1',header=[1])
df = df.rename(columns={'Unnamed: 1':'country'})
df = df[df['country'].isin(countries)]
df.columns

Index(['Region/Country/Area', 'country', 'Series', 'Year', 'Value',
       'Footnotes', 'Source'],
      dtype='object')

In [23]:
df = df[df['Series']=='Index of industrial production: Manufacturing (Index base: 2005=100)']
df = df.rename(columns={'Value':'Manufacturing'})
dfmanu = df[['country', 'Year', 'Manufacturing']]
del df

In [27]:
data_frames = [df_internet,dfcpi,dfimex,dfcrime,dfmig,dfgdp,dftour,dfedu,dfmanu]

from functools import reduce
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['country', 'Year'],
                                            how='outer'), data_frames)
cols = df_merged.loc[:, df_merged.dtypes == object].columns

def func(x):
    try:
        return x.replace(',','')
    except:
        return x

for i in cols:
    df_merged[i] = df_merged[i].apply(func)
df_merged.shape

(2768, 15)

In [28]:
df_merged

,country,Year,internetusage,CPIG,CPIF,Imports,Exports,homicide,migrants,GDP,PPP,tourexp,tvarrival,education,Manufacturing
0,Afghanistan,2005,1.2,NaN,NaN,NaN,NaN,NaN,0.3,6622,264,NaN,NaN,NaN,NaN
1,Afghanistan,2010,4.0,NaN,NaN,5154,388,3.4,0.4,16078,558,NaN,NaN,17.0676,NaN
2,Afghanistan,2014,7.0,133.1,101.7,7697,571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,2015,8.3,132.1,100.8,7723,571,NaN,1.5,20608,611,NaN,NaN,12.5090,NaN
4,Afghanistan,2016,10.6,137.9,106.5,6534,596,NaN,NaN,20235,584,NaN,NaN,NaN,NaN
5,Afghanistan,2017,11.4,144.8,113.9,7384,700,NaN,0.4,21993,619,NaN,NaN,15.6614,NaN
6,Albania,2000,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Albania,2005,6.0,86.7,82.8,2614,658,5.0,2.1,8052,2615,NaN,NaN,11.3580,NaN
8,Albania,2010,45.0,100,100,4603,1550,4.3,1.8,11927,4056,1778,2191,NaN,186.6
9,Albania,2014,60.1,109.3,113.8,5230,2431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,212.9
10,Albania,2015,63.3,111.4,118.8,4320,1930,2.3,1.8,11387,3895,1613,3784,11.3177,NaN
11,Albania,2016,66.4,112.8,122.6,4669,1962,2.7,NaN,11884,4061,1820,4070,13.5970,NaN
12,Albania,2017,71.8,115.1,127.3,5826,2262,NaN,1.8,13039,4450,2049,4643,NaN,NaN
13,Algeria,2000,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Algeria,2005,5.8,NaN,NaN,20357,46002,0.6,0.6,103198,3100,477,1443,NaN,NaN
15,Algeria,2010,12.5,100,100,41000,57051,0.7,0.6,161207,4463,324,2070,NaN,85.5
16,Algeria,2014,29.5,120.9,125.4,58618,60388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.4
17,Algeria,2015,38.2,126.7,131.3,51803,34796,1.4,0.6,165979,4163,347,1710,NaN,NaN
18,Algeria,2016,42.9,134.8,135.7,47091,29992,NaN,NaN,160130,3943,246,2039,NaN,NaN
19,Algeria,2017,47.7,142.4,142.5,46053,35191,NaN,0.6,167555,4055,172,2451,NaN,NaN
20,Andorra,2000,10.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Andorra,2005,37.6,89.6,92,1796,143,NaN,63.8,3256,41281,NaN,NaN,NaN,NaN
22,Andorra,2010,81.0,100,100,1541,92,NaN,61.6,3355,39734,NaN,NaN,NaN,NaN
23,Andorra,2014,95.9,104.4,106.4,1556,95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Andorra,2015,96.9,103.3,108.2,1295,87,NaN,53.9,2812,36040,NaN,NaN,NaN,NaN
25,Andorra,2016,97.9,102.8,109.1,1355,100,NaN,NaN,2877,37230,NaN,NaN,NaN,NaN
26,Andorra,2017,98.9,105.5,112.3,1480,120,NaN,53.3,3013,39153,NaN,NaN,NaN,NaN
27,Angola,2000,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Angola,2005,1.1,53.7,45.5,8321,23835,NaN,0.3,36971,1891,103,210,7.9924,NaN
29,Angola,2010,2.8,100,100,18143,52612,NaN,0.3,83799,3586,726,425,8.6848,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2738,Uganda,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153.7
2739,Uganda,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.2
2740,Ukraine,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.5
2741,Ukraine,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.3
2742,Ukraine,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.9
2743,Ukraine,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.3
2744,United Kingdom,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103.0
2745,United Kingdom,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0
2746,United Kingdom,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.6
2747,United Kingdom,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.6
2748,United Kingdom,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.4
2749,United Kingdom,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.9
2750,Uruguay,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115.7
2751,Uruguay,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129.7
2752,Uruguay,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.6
2753,Uruguay,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.2
2754,Uruguay,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.7
2755,Venezuela (Boliv. Rep. of),2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,117.7
2756,Venezuela (Boliv. Rep. of),2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.3
2757,Venezuela (Boliv. Rep. of),2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.1
2758,Venezuela (Boliv. Rep. of),2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.3
2759,Viet Nam,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,183.3
2760,Zambia,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110.2
2761,Zambia,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.9
2762,Zambia,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.4
2763,Zambia,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,142.4
2764,Zambia,2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.5
2765,Zimbabwe,2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.9
2766,Zimbabwe,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.2
2767,Zimbabwe,2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.2